
language : scala

scala:
  - 2.11.12
  - 2.12.9
  - 2.13.0

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

jdk:
  - openjdk8

script:
  - sbt -Dfile.encoding=UTF8 "project allProtocols" "++$TRAVIS_SCALA_VERSION test"


